### ISSUE TITLE
Revisar la Ley sobre el acceso a la información pública a través de bases de datos, y documentar que se cumpla en las acciones a la base de datos realizada.

### ISSUE THREAD

**Issue by fedeguzani** [fedeguzani/TSIT4.0G12#4]

**Comment by mario8971** [comment]
Ley sobre el acceso a la información pública
Ley 26.653
Hoy vivimos en una era de innovación que se esta desarrollando a nivel global. Es decir, en todos los países.
Esta acción de ideas y vanguardias, tienen una premisa fundamental, que es la renovación, la mejora de procesos y los reemplazos constantes. De esta manera, es donde se empieza a incrementar la innovación a través de la accesibilidad. 
La accesibilidad o accesibilidad universal es el grado que permite que cualquier objeto sea utilizado por todo el publico, visitar un lugar o acceder a un servicio, independientemente de sus capacidades técnicas, cognitivas o físicas. 
En la ley mencionada el argumento principal, ( Art 1) describe las normas y los requisitos, sobre los diseños en paginas web. Estos requisitos deben otorgar con facilidad el acceso a la información a todas las personas con discapacidad garantizando la igualdad real de oportunidades, evitando así todo tipo  de de discrimancion.
En nuestro caso no menciona una pagina web. Y el requerimiento es desarrollar una calculadora. Nosotros como programadores, tenemos la responsabilidad, que el desarrollo sea optimo y accesible como menciona la ley en dicho caso. Es decir, el uso de la calculadora, es de practica interna de la empresa y ahí empiezan a jugar varios factores. 
Nuestra base de datos es simple y de fácil acceso. Por ende, esto hace que la calculadora sea de usabilidad accesible para todas las personas.
